count_citation:
-   min: 12
    max: 12
    cite: "a dozen"
-   min: 17
    max: 19
    cite: "nearly a score of"
-   min: 20
    max: 20
    cite: "a score of"
-   min: 24
    max: 24
    cite: "two dozen"
-   min: 33
    max: 35
    cite: "nearly three dozen"
-   min: 36
    max: 36
    cite: "three dozen"
-   min: 37
    max: 39
    cite: "nearly two score"
-   min: 40
    max: 40
    cite: "two score"
