== Field Show - Open

Good afternoon ladies and gentlemen.
Welcome to the Field Show Competition for the {{show.citation}}.
We are joined today by {{fieldshow._count.citation}} talented bands anxious to perform.
On behalf of Foothill High School, we wish good luck to all the bands performing today and hope you enjoy their shows.

<<<

{{#each fieldshow.lineup}}
{{#if ref}}
{{> field-entry school=(lookup ../_schools ref) unit=(lookup (lookup ../_schools ref) 'fieldshow') isFirst=@first}}
{{else}} {{#if break}}
{{> program-break competition="Field Show" break=break}}
{{/if}} {{/if}}

<<<

{{/each}}

== Field Show - Close

This concludes the Field Show Competition for the {{show.citation}}.
Please stay for the Field Show Awards, presented here in 15 minutes.

Whether you're from Foothill or cheering your home school, you probably know how much work it takes to hold a successful band review, where student performers can share their talent with and their love of music.
Today, {{parade._count.number}} bands marched in parade, {{concert._count.number}} performed in concert, and {{fieldshow._count.number}} presented field shows.
All this would not happen without the work of several hundred student and parent volunteers.
Foothill High School thanks everyone who contributed to the success of today's Band Review.
You all made it happen!

<<<

== Field Show - Awards

{{#unless fieldshow.sponsors.general}}IMPORTANT: There are no field show sponsors.
{{/unless}}
{{#unless fieldshow.sponsors.trophies}}IMPORTANT: There are no field show sponsors.
{{/unless}}

Foothill High School thanks the sponsors of the {{show.citation}}: {{#each fieldshow.sponsors.general}}{{#unless @first}}, {{#if @last}}and {{/if}}{{/unless}}{{{.}}}{{/each}}.

(General award announcement)
With a score of {score}, {nth} place {category} goes to [pause] {name of school}!

{{> trophy-sponsors trophies=fieldshow.sponsors.trophies}}

<<<
