== Winter Guard - {{unit.schoolName}}{{#unless unit._upToDate}} - MISSING DATA{{/unless}}

{{#unless unit._upToDate}}IMPORTANT: {{unit.schoolName}} data is out of date.
{{/unless}}
{{#unless unit.program}}WARNING: {{unit.schoolName}} is missing a program name.
{{/unless}}
{{#unless unit.directors}}WARNING: {{unit.schoolName}} has no directors.
{{/unless}}
{{#unless unit.leaders}}WARNING: {{unit.schoolName}} has no leaders.
{{/unless}}
{{#unless unit.nickname}}WARNING: {{unit.schoolName}} is missing a nickname.
{{/unless}}

NOTE: Last updated {{unit._lastUpdated}}

Now taking the floor is {{#if unit.isHost}}your host, {{/if}}the {{unit.nickname}}, from {{unit.schoolName}} in {{unit.city}}.

{{> leaders unit=unit}}

{{#if unit.program}}
The {{unit.nickname}} will perform their program, {{{unit.program}}}{{#if unit.music}}, featuring {{{unit.music}}}{{/if}}.
{{else}}{{#if unit.music}}
The {{unit.nickname}} will perform a program featuring {{{unit.music}}}.
{{/if}}{{/if}}

{{#if unit.notes}}{{{unit.notes}}}{{else}}NOTE: {{unit.schoolName}} has no guard notes.{{/if}}

(wait for cue from judge) +
Are the judges ready? (wait for cue from judge) +
{{unit.schoolName}}, is your guard unit ready? (wait for cue from judge) +
Performing their {{year}} show, {{#if unit.program}}{{{unit.program}}},{{/if}} NCBA is proud to present the {{unit.nickname}}.
