== Parade - Open

Good morning ladies and gentlemen.
Welcome to the Parade Competition for the {{show.citation}}.
We are joined today by {{parade._count.citation}} wonderful bands to entertain and delight us.
On behalf of Foothill High School, we wish good luck to all the bands performing today and hope you enjoy the competition.

<<<

== Parade - Grand Marshal

Leading off today's parade, please welcome our {{parade.grand_marshall.title}}, {{#each parade.grand_marshall.members}}{{#unless @first}}, {{#if @last}}and {{/if}}{{/unless}}{{.}}{{/each}}.

<<<

== Parade - Presentation of the Colors

At this time, please rise and give respect to the colors, presented by by {{parade.colors}}.

<<<

{{#each parade.lineup}}
{{#if break}}
{{> program-break competition="Parade" break=break}}
{{else}}
{{> parade-entry unit=. isFirst=@first}}
{{/if}}

<<<

{{/each}}

== Parade - Close

This concludes the Parade Competition for the {{show.citation}}.
Thank you and congratulations to all the bands we've seen this morning, and thank you all for attending and cheering on these fine young performers.

Parade Awards will be presented at {{parade.awards_time}} in the {{parade.awards_location}}.

Please join us at the Foothill High School Stadium for the Field Show Competition, starting at {{fieldshow.start_time}} this afternoon and running through this evening.

Mark your calendars to join us again next year, on {{next_show.date}}, for the {{next_show.citation}}.
On behalf of Foothill High School, I wish you all a safe and enjoyable weekend.
Good day.

<<<

== Parade and Concert - Awards

{{#unless parade.sponsors.general}}NOTE: There are no parade sponsors.
{{/unless}}
{{#unless parade.sponsors.trophies}}NOTE: There are no parade trophy sponsors.
{{/unless}}

Foothill High School thanks the sponsors of the {{show.citation}}: +
{{#each parade.sponsors.general}}{{#unless @first}}, +
{{#if @last}}and {{/if}}{{/unless}}{{{.}}}{{/each}}.

{{> trophy-sponsors trophies=parade.sponsors.trophies }}

(announce scores and awards for Parade and Concert)

<<<
