== Parade - {{school.name}}

{{#unless school.parade.music}}WARNING: {{{school.name}}} is missing parade music.{{/unless}}
{{#unless school.parade.directors}}WARNING: {{{school.name}}} has no directors.{{/unless}}
{{#unless school.parade.leaders}}WARNING: {{{school.name}}} has no leaders.{{/unless}}
{{#unless school.parade.nickname}}NOTE: {{{school.name}}} is missing nickname.{{/unless}}

Our {{#if isFirst}}first{{else}}next{{/if}} band is the {{{school.parade.nickname}}}, from {{{school.name}}} in {{{school.city}}}.

The {{{school.parade.nickname}}} is directed by {{#each school.parade.directors}}{{#unless @first}}, {{#if @last}}and {{/if}}{{/unless}}{{.}}{{/each}}{{#each school.parade.staff}}, +
{{#if @last}}and {{/if}}{{{title}}} {{#each members}}{{#unless @first}}, {{#if @last}}and {{/if}}{{/unless}}{{{.}}}
{{/each}}{{/each}}
{{#each school.parade.leaders}}{{#if @first}}and led by +
{{/if}}{{#unless @first}}, +
{{/unless}}{{#unless @first}}{{#if @last}}and {{/if}}{{/unless}}{{{title}}} {{#each members}}{{#unless @first}}, {{#if @last}}and {{/if}}{{/unless}}{{{.}}}
{{/each}}{{/each}}.

The {{{school.parade.nickname}}} will perform {{{school.parade.music}}}.

{{#if school.parade.notes}}{{{school.parade.notes}}}{{else}}NOTE: {{{school.name}}} has no parade notes.{{/if}}
