== Winter Percussion - {{school.name}}{{#unless unit._upToDate}} - INCOMPLETE{{/unless}}

{{#unless unit}}IMPORTANT: {{school.name}} has no unit.
{{/unless}}
{{#unless unit._upToDate}}IMPORTANT: {{school.name}} data is out of date.
{{/unless}}
{{#unless unit.program}}WARNING: {{school.name}} is missing a program name.
{{/unless}}
{{#unless unit.directors}}WARNING: {{school.name}} has no directors.
{{/unless}}
{{#unless unit.leaders}}WARNING: {{school.name}} has no leaders.
{{/unless}}
{{#unless unit.nickname}}WARNING: {{school.name}} is missing a nickname.
{{/unless}}

Now taking the floor is the {{unit.nickname}}, from {{school.name}} in {{school.city}}.

{{> leaders unit=unit}}

The {{unit.nickname}} will perform their program, {{{unit.program}}}{{#if unit.music}}, featuring {{unit.music}}{{/if}}.

{{#if unit.notes}}{{{unit.notes}}}{{else}}NOTE: {{school.name}} has no percussion notes.{{/if}}

(wait for cue from judge) +
Are the judges ready? (wait for cue from judge) +
{{school.name}}, is your percussion unit ready? (wait for cue from judge) +
Performing their {{year}} show, {{{unit.program}}}, NCBA is proud to present the {{unit.nickname}}.
