== Winter Percussion - Open

Good morning ladies and gentlemen. Welcome to the Percussion Competition for
the {{show.citation}}. We are joined today by {{winterpercussion._count.citation}} talented
units anxious to perform and entertain. On behalf of Foothill High School, we wish good luck
to all the units performing today and hope you enjoy their shows.

<<<

{{#each winterpercussion.lineup}}
{{#if ref}}
{{#if unit}}
{{> percussion-entry school=(lookup ../_schools ref) unit=(lookup (lookup ../_schools ref) unit) year=../show.year isFirst=@first}}
{{else}}
{{> percussion-entry school=(lookup ../_schools ref) unit=(lookup (lookup ../_schools ref) 'winterpercussion') year=../show.year isFirst=@first}}
{{/if}}
{{else}} {{#if break}}
{{> program-break competition="Winter Percussion" break=break}}
{{/if}} {{/if}}

<<<

{{/each}}

== Winter Percussion - End of Competition

This concludes the Percussion Competition for the {{show.citation}}.
Please stay for the Percussion Awards, presented here in 20 minutes, and for the Color Guard competition,
beginning at {{winterguard.start_time}}.

<<<

== Winter Percussion - Awards

{{#unless winterpercussion.sponsors.general}}IMPORTANT: There are no winter percussion sponsors.
{{/unless}}
{{#unless winterpercussion.sponsors.trophies}}IMPORTANT: There are no winter percussion sponsors.
{{/unless}}

Foothill High School thanks the sponsors of the {{show.citation}}: {{#each winterpercussion.sponsors.general}}{{#unless @first}}, {{#if @last}}and {{/if}}{{/unless}}{{{.}}}{{/each}}.

(General award announcement)
With a score of {score}, {nth} place {category} goes to [pause] {name of school}!

{{> trophy-sponsors trophies=winterpercussion.sponsors.trophies}}

<<<
