== Winter Percussion - {{unit.schoolName}}{{#unless unit._upToDate}} - MISSING DATA{{/unless}}

{{#unless unit._upToDate}}IMPORTANT: {{unit.schoolName}} data is out of date.
{{/unless}}
{{#unless unit.program}}WARNING: {{unit.schoolName}} is missing a program name.
{{/unless}}
{{#unless unit.directors}}WARNING: {{unit.schoolName}} has no directors.
{{/unless}}
{{#unless unit.leaders}}WARNING: {{unit.schoolName}} has no leaders.
{{/unless}}
{{#unless unit.nickname}}WARNING: {{unit.schoolName}} is missing a nickname.
{{/unless}}

NOTE: Last updated {{unit._lastUpdated}}

Now taking the floor is {{#if unit.isHost}}your host, {{/if}}the {{unit.nickname}}, from {{unit.schoolName}} in {{unit.city}}.

{{> leaders unit=unit}}

The {{unit.nickname}} will perform their program, {{{unit.program}}}{{#if unit.music}}, featuring {{{unit.music}}}{{/if}}.

{{#if unit.notes}}{{{unit.notes}}}{{else}}NOTE: {{unit.schoolName}} has no percussion notes.{{/if}}

(wait for cue from judge) +
Are the judges ready? (wait for cue from judge) +
{{unit.schoolName}}, is your percussion unit ready? (wait for cue from judge) +
Performing their {{year}} show, {{{unit.program}}}, NCBA is proud to present the {{unit.nickname}}.
